import Head from "next/head";
import React, { useRef, useState } from "react";

// Common CSS
import Header from '../../../Components/theme_1/Common/Header';
import MenuBar from '../../../Components/theme_1/Common/Menubar';
import Delivary from '../../../Components/theme_1/Common/Delivary';
import Footer from '../../../Components/theme_1/Common/Footer';
import SocialMedia from '../../../Components/theme_1/Common/SocialMedia';
import TinyFooter from '../../../Components/theme_1/Common/TinyFooter';
import ShippingAddress from "../../../Components/theme_1/ShippingAddress/ShippingAddress";
import { Editor, Frame } from "@craftjs/core";


const index = () => {
	return (
		<>

			<Head>

				<title>Sales Solution Theme_1</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="frontend_asset/images/Logo.png" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />

			</Head>

			<main>                                     m                         

				<Header></Header>
				<Editor resolver={{ MenuBar }}>
					<Frame>
						<MenuBar menu1={'Home'} menu2={'Shop'} menu3={'About Us'} menu4={'Contact Us'} fontSize={'15'} />
					</Frame>
				</Editor>

				<ShippingAddress></ShippingAddress>

				<Delivary></Delivary>
				<Footer></Footer>
				<SocialMedia></SocialMedia>
				<TinyFooter></TinyFooter>


			</main>

			<footer>

			</footer>

		</>
	);
};

export default index;