import style from "/styles/Register.module.css";
import Link from "next/link";
import * as yup from "yup";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import axios from "axios";
import { baseUrl } from "../constant/constant";
import { useRouter } from "next/router";
import { useState } from "react";
import Otp from "../Components/Otp/Otp";
import { toast } from "react-toastify";
import Head from "next/head";

export default function Signup() {
  const router = useRouter();
  const phoneRegex = /^(?:\+88|88)?(01[3-9]\d{8})$/;
  const [loading, setLoading] = useState(false);
  const [phone, setPhone] = useState(null);
  const [verifyLoading, setVerifyLoading] = useState(false);

  const validationSchema = yup.object().shape({
    name: yup.string().required("Full name field is required"),
    email: yup.string().required("Email field is required").email(),
    phone: yup
      .string()
      .required("Phone field is required")
      .matches(phoneRegex, "Phone number is not valid"),
    shop_name: yup.string().required("Shop name field is required"),
    password: yup.string().required("Password field is required"),
    password_confirmation: yup
      .string()
      .required("Confirm Password field is required")
      .oneOf([yup.ref("password"), null], "Passwords must match"),
  });

  const {
    register,
    handleSubmit,
    watch,
    setError,
    formState: { errors },
  } = useForm({
    mode: "onChange",
    resolver: yupResolver(validationSchema),
  });

  const submitForm = (data) => {
    setLoading(true);

    axios
      .post(baseUrl + "/api/v1/signup", data)
      .then((response) => {
        if (response.data.success === true) {
          setVerifyLoading(true);
          setPhone(response?.data?.data?.phone);
          toast.success(response.data.message, {
            position: toast.POSITION.TOP_CENTER,
            onClose: () => {
              // setPhone(response.data.data.phone)
              setLoading(false);
              setVerifyLoading(true);
            },
          });
        }
      })
      .catch((errors) => {
        Object.keys(errors.response.data.errors).forEach((field) => {
          const messages = errors.response.data.errors[field];

          setError(field, {
            type: "server",
            message: messages.join(". "),
          });
        });
        setLoading(false);
      });
  };

  return (
    <>
      <Head>
        <title>Funnel Liner | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, user-scalable=no" />
        <link rel="icon" href="../images/favicon.png" />
      </Head>
      <div></div>
      <div>
        {!verifyLoading ? (
          <section className={style.Register}>
            <div className={style.RegisterForm}>
              <div className={style.Overflow}>
                <div className={style.HeaderPart}>
                  <div className="Logo">
                    <img
                      src="/images/logo_1.svg"
                      alt=""
                      className={style.RegisterFormLogo}
                    />
                  </div>

                  <div className="text">
                    {/* <h3>Welcome To </h3> */}
                    <p>
                      The Best Business 360 Solution For Your Business, <br /> Just
                      Login & You’re Ready To Go !
                    </p>
                  </div>
                </div>

                <form onSubmit={handleSubmit(submitForm)}>
                  <div className={style.form_part}>
                    <div className={style.CustomerInput}>
                      <label
                        className={`${
                          errors.name ? `${style.ValidationErrorLabel}` : ""
                        }`}
                      >
                        Full Name <span>*</span>
                      </label>
                      <input
                        type="text"
                        name="name"
                        className={`${
                          errors.name
                            ? `${style.CustomerInputField} ${style.ValidationError}`
                            : `${style.CustomerInputField}`
                        }`}
                        placeholder="Enter Your Full Name "
                        {...register("name")}
                      />
                      {errors && (
                        <span className={style.ValidationErrorLabel}>
                          {errors.name?.message}
                        </span>
                      )}
                    </div>

                    <div className={style.CustomerInput}>
                      <label
                        className={`${
                          errors.shop_name
                            ? `${style.ValidationErrorLabel}`
                            : ""
                        }`}
                      >
                        Shop Name <span>*</span>
                      </label>
                      <input
                        type="text"
                        name="name"
                        className={`${
                          errors.shop_name
                            ? `${style.CustomerInputField} ${style.ValidationError}`
                            : `${style.CustomerInputField}`
                        }`}
                        placeholder="Enter Your Shop Name "
                        {...register("shop_name")}
                      />

                      {errors && (
                        <span className={style.ValidationErrorLabel}>
                          {errors.shop_name?.message}
                        </span>
                      )}
                    </div>

                    <div className={style.CustomerInput}>
                      <label
                        className={`${
                          errors.email ? `${style.ValidationErrorLabel}` : ""
                        }`}
                      >
                        E-mail Address <span>*</span>
                      </label>
                      <input
                        type="text"
                        className={`${
                          errors.email
                            ? `${style.CustomerInputField} ${style.ValidationError}`
                            : `${style.CustomerInputField}`
                        }`}
                        placeholder="Enter Your Email Address "
                        {...register("email")}
                      />

                      {errors && (
                        <span className={style.ValidationErrorLabel}>
                          {errors.email?.message}
                        </span>
                      )}
                    </div>

                    <div className={style.CustomerInput}>
                      <label
                        className={`${
                          errors.phone ? `${style.ValidationErrorLabel}` : ""
                        }`}
                      >
                        Phone Number <span>*</span>
                      </label>
                      <input
                        type="text"
                        className={`${
                          errors.phone
                            ? `${style.CustomerInputField} ${style.ValidationError}`
                            : `${style.CustomerInputField}`
                        }`}
                        placeholder="Enter Your Phone Number "
                        {...register("phone")}
                      />

                      {errors && (
                        <span className={style.ValidationErrorLabel}>
                          {errors.phone?.message}
                        </span>
                      )}
                    </div>

                    <div className={style.CustomerInput}>
                      <label
                        className={`${
                          errors.password ? `${style.ValidationErrorLabel}` : ""
                        }`}
                      >
                        Password <span>*</span>
                      </label>
                      <input
                        type="password"
                        name="name"
                        className={`${
                          errors.password
                            ? `${style.CustomerInputField} ${style.ValidationError}`
                            : `${style.CustomerInputField}`
                        }`}
                        placeholder="Enter Your Password "
                        {...register("password")}
                      />

                      {errors && (
                        <span className={style.ValidationErrorLabel}>
                          {errors.password?.message}
                        </span>
                      )}
                    </div>

                    <div className={style.CustomerInput}>
                      <label
                        className={`${
                          errors.password_confirmation
                            ? `${style.ValidationErrorLabel}`
                            : ""
                        }`}
                      >
                        Confirm Password <span>*</span>
                      </label>
                      <input
                        type="password"
                        name="name"
                        className={`${
                          errors.password_confirmation
                            ? `${style.CustomerInputField} ${style.ValidationError}`
                            : `${style.CustomerInputField}`
                        }`}
                        placeholder="Confirm Your Password"
                        {...register("password_confirmation")}
                      />

                      {errors && (
                        <span className={style.ValidationErrorLabel}>
                          {errors.password_confirmation?.message}
                        </span>
                      )}
                    </div>
                  </div>

                  <div className={style.Button}>
                    <button
                      type="submit"
                      className={style.CustomerInputButton}
                      disabled={loading}
                    >
                      {!loading ? "Register" : "Creating Account ..."}
                    </button>

                    <p className={style.CustomerInputPara}>
                      Already have an account ?
                      <Link
                        className={style.CustomerInputLink}
                        href={"https://dashboard.funnelliner.com/"}
                      >
                        Login
                      </Link>
                    </p>
                  </div>
                </form>
              </div>
            </div>
          </section>
        ) : (
          <Otp phone={phone} />
        )}
      </div>
    </>
  );
}
